---
emailName: David
emailAddresses:
    - sillymoos@cpan.org
    - perltricks.com@gmail.com
credentials:
    username: sillymoose
    password: itsasecret
sqlfile: sql.json
DSN : "CHaviation"
steps:
  - task:
      inputs:
        type: 'execute'
        dbfile: '.\database.accdb'
        sql: '0'
        script: '.\execute.pl'
  - task:
      inputs:
        type: 'import'
        table: 'Working_Hours_PurelyHR'
        file: 'DetailsReport_20200101-20200229.csv'
        import: 'Import Working_Hours_PurelyHR'
        sql: 'Import Working_Hours_PurelyHR'
        dbfile: 'database.accdb'
        script: '.\import.pl'